### ISSUE TITLE
consider building standalone binaries using travis

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#109]
pip install pyinstaller and generate the linux standalone binaries during testing. upload to S3 described here: https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by williballenthin** [comment]
but this would only include linux binaries. not sure you can cross compile with pyinstaller.

**Comment by williballenthin** [comment]
pyinstaller recommends running under wine to build windows binaries from linux. this would be feasible.

**Comment by mr-tz** [comment]
running the tests on the standalone binaries would be great to show that they achieve the same results

**Comment by williballenthin** [comment]
example: https://s3.amazonaws.com/build-artifacts.floss.flare.fireeye.com/fireeye/flare-floss/48/48.1/dist/floss

**Comment by williballenthin** [comment]
closed in fd0813435df24240ff382d49b63f22510c0da9a6
