### ISSUE TITLE
Improve output if run on non-PE file (-a switch)

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-floss#119]
Improve user feedback if run on non-PE file.
We still extract static strings if run with the `-a` option, but decoding doesn't work for it.

**Comment by williballenthin** [comment]
floss already extracts static strings from non-PE files if `-a` is provided

**Comment by williballenthin** [comment]
implemented in branch, but wondering if automatically extracting strings from unsupported file types might confuse people (make them think the tool is working when its not?).

its inconsistent to sometimes require `-a` and other times not.

perhaps instead floss should provide a suggestion to the user.

**Comment by williballenthin** [comment]
updated branch. now suggests to use `-a` if not provided, rather than implicitly changing the mode.
