### ISSUE TITLE
ensure using 64bit emulator for 64bit binaries

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#120]
want to use `Amd64WorkspaceEmulator`:
https://github.com/vivisect/vivisect/blob/master/vivisect/impemu/platarch/amd64.py

need to confirm the emulator is detected and created correctly

**Comment by mr-tz** [comment]
It's using the correct emulator

**Comment by mr-tz** [comment]
Issues were related to bug in vivisect (see https://github.com/vivisect/vivisect/pull/128)

**Comment by williballenthin** [comment]
need to merge this into williballenthin/vivisect

**Comment by williballenthin** [comment]
i've merged vivisect 128 into my fork of vivisect
