### ISSUE TITLE
print_all_strings() errors when not in quite mode

### ISSUE THREAD

**Issue by hiddenillusion** [fireeye/flare-floss#121]
Within **main.py** , `print_all_strings()` incorrectly handles the *ascii_strings* and *uni_strings* generators when `quiet=False`.

lines [406](https://github.com/fireeye/flare-floss/blob/master/floss/main.py#L406) and [416](https://github.com/fireeye/flare-floss/blob/master/floss/main.py#L416) both check the len() of their respective extract function within **strings** instead of checking if they exist and/or just iterating their contents like how they're handled when `-a` and `-q` are both selected.

Traceback:
```
user: ~/Desktop $ floss -a test.exe 
Static ASCII strings
Traceback (most recent call last):
  File "/usr/local/bin/floss", line 9, in <module>
    load_entry_point('floss==1.1.0', 'console_scripts', 'floss')()
  File "/usr/local/lib/python2.7/dist-packages/floss/main.py", line 466, in main
    print_all_strings(sample_file_path, min_length=min_length, quiet=options.quiet)
  File "/usr/local/lib/python2.7/dist-packages/floss/main.py", line 406, in print_all_strings
    if len(ascii_strings) == 0:
TypeError: object of type 'generator' has no len()
```

**Comment by williballenthin** [comment]
ah, yeah, need to wrap the calls on lines 404 and 414 in `list(..)`. good catch. thanks!
