### ISSUE TITLE
Make API hooks independent from calling convention

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-floss#124]
Currently `RtlAllocateHeapHook`, `AllocateHeap`, and `MallocHeap` only focus on the `__stdcall` calling convention.

**Comment by williballenthin** [comment]
probably can use the `argv` parameter to the function to make these hooks independent of calling convention

https://github.com/fireeye/flare-floss/blob/master/floss/decoding_manager.py#L217

**Comment by williballenthin** [comment]
need to create a regression test case for this issue
