### ISSUE TITLE
Error/Exception in parsing a memory image

### ISSUE THREAD

**Issue by cteodor** [fireeye/flare-floss#128]
>c:\bin\floss.exe -a mem.bin > mem.strings
Traceback (most recent call last):
  File "<string>", line 409, in <module>
  File "<string>", line 365, in main
  File "<string>", line 307, in print_all_strings
SystemError: ..\Objects\stringobject.c:3901: bad argument to internal function
main returned -1

Not sure how to reproduce, as mem.bin is 32G

**Comment by williballenthin** [comment]
thanks @cteodor for reporting this issue. we'll update FLOSS to ensure that it will at least print static strings when the file size exceeds available memory.

would you confirm the file type of `mem.bin`? is this a PE file? or a memory image?

**Comment by williballenthin** [comment]
opened issue #129: should extract static strings regardless of input file size

**Comment by williballenthin** [comment]
ah, i see in the title this is a memory image, sorry for the extra question.

this is a good issue, and we'll work on it in #129

**Comment by williballenthin** [comment]
also #132

**Comment by williballenthin** [comment]
#119 seems related

**Comment by williballenthin** [comment]
should be closed in 6b4d293. try using FLOSS from source (immediately), or a nightly build starting tomorrow. we'll have a new version (1.3) available on Friday that will included this fix.
