### ISSUE TITLE
Maybe don't run stackstrings on every function

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-floss#130]
Running stackstrings on every function might take a lot of time and memory for binaries with many/big functions. We could limit the scope by adding a stackstrings identification plugin.

**Comment by williballenthin** [comment]
> might take a lot of time

it *shouldn't* take significantly longer than a second pass of brute force analysis. if it does, something is wrong :-).

i agree something might be up with the memory usage, esp if there are many function calls and lots of data on the stack. might be worth de-duping strings on the stack at an earlier point, if its the issue.

**Comment by williballenthin** [comment]
do we have a testcase for this?

**Comment by williballenthin** [comment]
@mr-tz haven't seen this be a practical issue. thoughts on closing this unless we have a test case?

**Comment by mr-tz** [comment]
I agree. I guess it came up with the memory errors and the missing sanity checking that should be fixed now.
