### ISSUE TITLE
FLOSS should extract static strings from binary data via stdin

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#131]
should be able to pipe data to FLOSS and have it extract *some* strings.

not sure if it should serialize a PE to a temp file and extract obfuscated strings? or just do static strings (if enabled?). 

if like this:

    cat ntdll.dll | floss.exe

should read from stdin

if like this:

    cat ntdll.dll | floss.exe -a -

should interpret `-` as "please use stdin".

**Comment by williballenthin** [comment]
@mr-tz thoughts?

**Comment by mr-tz** [comment]
I'd say if data is piped to FLOSS, it should only do static strings. So, the first invocation looks good.

**Comment by williballenthin** [comment]
ok, sounds good. lets warn the user via stderr that only static strings will be extracted.

**Comment by mr-tz** [comment]
I was just about to add that...

**Comment by williballenthin** [comment]
turns out this is not that easy. we read the ascii and unicode strings in two passes. when data is piped in, we don't get to seek around, so its difficult to do both ascii and unicode strings.

adding support for this will require lots of code changes, more complexity. not sure that its worth it right now.

willing to re-open for discussion.

**Comment by mr-tz** [comment]
Although it would be a cool feature, we should not worry about it for now given the complex code changes.
