### ISSUE TITLE
IntervalTree error (viv-utils?)

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-floss#150]
Error: `ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree`

Samples:
  - `2eb589fb26d2dd8a2840949bae6be7f8`
  - `08d13c98c584c38d86f38b476d4a7fcd`
  - `af1e77d463d647d1350f2eb510be8c3c`

**Comment by williballenthin** [comment]
2eb589fb26d2dd8a2840949bae6be7f8 is a .NET PE

**Comment by williballenthin** [comment]
cant find af1e77d463d647d1350f2eb510be8c3c in MTA nor VT

**Comment by williballenthin** [comment]
can't find 08d13c98c584c38d86f38b476d4a7fcd in MTA nor VT

**Comment by williballenthin** [comment]
quickfix is to ensure `bb.size > 0` in viv-utils: https://github.mandiant.com/wballenthin/viv-utils/blob/master/viv_utils/__init__.py#L157

correct fix is to understand why we'd get BB with size 0

**Comment by williballenthin** [comment]
fixed upstream in viv-utils

https://github.mandiant.com/wballenthin/viv-utils/commit/f7a277350ecf888623646c685500c5a24f145732
