### ISSUE TITLE
remove .viv files, or write them to tmp directory so as not to pollute use directories.

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#161]
probably should create .viv file using md5sum of input file, not filename.

**Comment by williballenthin** [comment]
fixed upstream in `viv-utils` by adding the flag `should_save` to `getWorkspace`. once thats tagged and released to PyPI, update https://github.com/fireeye/flare-floss/blob/master/floss/main.py#L533 to provide `should_save=False` kwarg.

**Comment by williballenthin** [comment]
thanks to @pilate for the suggested patch

**Comment by mr-tz** [comment]
I see that this can be confusing (and even scary) for users, but like the speed up when running FLOSS multiple times. Do we want to add another option or have this be part of expert mode? :)

**Comment by mr-tz** [comment]
Ah, we can just provide the .viv workspace as input (#169). That works for me.
We'd still need an option to save the workspace initially though...

**Comment by williballenthin** [comment]
yeah, i think we should add a cli option, maybe `--save-workspace`, and include the .viv file generation in hardcore mode.

**Comment by williballenthin** [comment]
while us as devs may run floss on the same file multiple times, im not sure thats a common pattern for typical users. 

a compromise could be to put the .viv files in the temp directory.
