### ISSUE TITLE
flag "interesting" strings

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#163]
things like domains, filenames, ips, registry key fragments

highlight these things to bring attention to the user.

could highlight in a couple ways:
- colorize the output. sometimes this is annoying on windows. also, gets messy if you're piping the output to a file
- add "high value string" section reiterates interesting strings at the bottom of the output

**Comment by williballenthin** [comment]
pestudio does something similar: https://www.winitor.com/

**Comment by williballenthin** [comment]
how to specify "interesting strings"? should it be extensible?

don't want to over engineer, so leaning towards no, with PRs welcome to the source to enable more matchers.

**Comment by williballenthin** [comment]
cc @0xF2EDCA5A

**Comment by Maijin** [comment]
Would be more useful imho to blacklist strings than creating "YET" another "interesting" string database.

**Comment by Maijin** [comment]
And maybe just let the possibility to the user to give input a list of string in txt file.

**Comment by williballenthin** [comment]
fe38f105613c7356b4521a1f250c470c0592fe2f add support for better filter for FP strings, which is the best we're going to do in this project.

don't want to re-invent the wheel of "interesting strings database" as @Maijin pointed out.
