### ISSUE TITLE
should FLOSS output addresses by default?

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#164]
currently FLOSS displays the encoding routine addresses and encoded string VAs in the output. this is probably only useful to a reverse engineer

**Comment by williballenthin** [comment]
the `-g` option groups output by decoding routine, which helps even a basic user understand how many decoding routines there are in a sample. this is interesting, though potentially not actually helpful.

**Comment by williballenthin** [comment]
the `-q` mode outputs without any formatting nor addresses, which is most like the default `strings.exe` output.

**Comment by mr-tz** [comment]
We could implement a basic mode and a advanced mode. Basic mode only gives you the plain string output (maybe some headers to indicate what is being displayed) and advanced mode provides a more detailed view. Analogous, we can group the command line switches for basic and advanced mode.

**Comment by williballenthin** [comment]
cc @0xF2EDCA5A

**Comment by williballenthin** [comment]
answer is yes, and merged in #227
