### ISSUE TITLE
handle vivisect error "Exception: Address (xxxx) not in maps!"

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#175]
see traceback here: https://gist.github.com/pilate/8e79a13c1ab9f9e7f5b2f01a4321ced6

i believe this is getting logged from within vivisect, so we may need to patch vivisect to suppress errors. alternatively, and better, is to identify the issue up front (malformed PE?) and better handle the case.

**Comment by williballenthin** [comment]
cc: @pilate

**Comment by mr-tz** [comment]
fixed in current vivisect/floss
