### ISSUE TITLE
failing test: test-decode-substitution-cipher::Windows::32bit

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-floss#202]
Decoding routine identification fails.
With #201 emulation works.

**Comment by williballenthin** [comment]
closed in 4a5017aad472875d4a2d821031cff7e61066ebbc

**Comment by williballenthin** [comment]
this is a detection issue

**Comment by williballenthin** [comment]
not sure how to solve...
current features are something like:

  - there is a loop
  - there's a call to memchr

this is not very much

**Comment by williballenthin** [comment]
perhaps the following instruction is interesting:

```
movsx   eax, byte ptr [ecx+eax]
```

add a new heuristic for: mov/fetch a single byte using a base pointer and offset

**Comment by williballenthin** [comment]
perhaps could use symbolic analysis to determine that the output buffer is a function of the input buffer. unsure of the feasibility. need johnk to complete his exploration of symboliks and provide some tutorials before we tackle this.
