### ISSUE TITLE
do performance regression testing for #204

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#205]
#204 may be much slower on some samples because `count` is implemented in pure Python. need to demonstrate there is not a serious performance regression. appropriate sample might be the one in #174 aa8a1c3afdf1d9b16fae80e6444d5889.

**Comment by shizhx** [comment]
1. should replace `range()` function with `xrange()` function
2. I did performance regression testing just now, it is **terrible**!

So, how to resolve this problem? `count` method is faster than pure python implement code, but `main.py` pass a `mmap object` as `buf` parameter, `mmap object` has no method `count`.

**Comment by williballenthin** [comment]
using `xrange` is a fine idea

**Comment by williballenthin** [comment]
what if we did something like:

```
def buf_filled_with(buf, c):
    if not hasattr(buf, 'count'):
        buf = bytes(buf)
    return buf.count(buf[0]) == len(buf)
```

**Comment by shizhx** [comment]
that sounds great

**Comment by shizhx** [comment]
Unfortunately, `bytes(mmap object)` doesn't seems to work
