### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by aquynh** [fireeye/flare-floss#233]
README has no information on how to install from source code (dont understand why such basic information is missing), so i tried:

```
$ sudo python setup.py install
...
Processing floss-1.3.0-py2.7.egg
removing '/Library/Python/2.7/site-packages/floss-1.3.0-py2.7.egg' (and everything under it)
creating /Library/Python/2.7/site-packages/floss-1.3.0-py2.7.egg
Extracting floss-1.3.0-py2.7.egg to /Library/Python/2.7/site-packages
floss 1.3.0 is already the active version in easy-install.pth
Installing floss script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/floss-1.3.0-py2.7.egg
Processing dependencies for floss==1.3.0
Searching for vivisect
Reading https://pypi.python.org/simple/vivisect/
No local packages or download links found for vivisect
error: Could not find suitable distribution for Requirement.parse('vivisect')

$
```

can you update README on how to install your tool? 

thanks.

**Comment by aquynh** [comment]
this is on Mac, if that matters.

**Comment by williballenthin** [comment]
both the github landing page and the readme links to the installation documentation found here: https://github.com/fireeye/flare-floss/blob/master/doc/installation.md

the basic user of FLOSS does not need to install the tool --- they can use the standalone binaries. this is why we don't include a tedious discussion of installation on the main readme. the documentation page for installation describes three different types of installations that are appropriate for different situations. please review these and let us know how you recommend we can improve the documentation.

**Comment by williballenthin** [comment]
your specific installation issue is due to the fact that vivisect is not available via pypi. the installation instructions cover the (easy) manual installation of this python package.

**Comment by williballenthin** [comment]
after reading the detailed documentation on installing, do you have any further issues?

**Comment by aquynh** [comment]
sorry for the late reply: yes it solved my issue.
but i still need to find more time to play with this.

thanks.
