### ISSUE TITLE
plugnplay license?

### ISSUE THREAD

**Issue by pombredanne** [fireeye/flare-floss#236]
Hi:
I saw that you depend on plugnplay by @daltonmatos which is GPL-licensed.
Is this an issue?  @daltonmatos would you consider a request to use another license more amenable to use plugnplay in this Apache-licensed library?

**Comment by daltonmatos** [comment]
No problem @pombredanne. Would a change to a BSD-3 license suffice?

https://opensource.org/licenses/BSD-3-Clause

**Comment by pombredanne** [comment]
@daltonmatos that would be perfect! Thank you for the quick reply!

**Comment by williballenthin** [comment]
good catch @pombredanne. 

i'm glad to hear that @daltonmatos is willing to update the license to BSD-3. that should make everything compatible (floss is apache 2 licensed).

**Comment by daltonmatos** [comment]
Hi, I just released a new version of plugnplay[1] which changes the license to BSD-3.

[1] https://pypi.python.org/pypi/plugnplay/0.5.3

**Comment by pombredanne** [comment]
@daltonmatos thank you for this swift and kind update!

**Comment by pombredanne** [comment]
@williballenthin wrote 
> good catch
well, I am consider this library as a replacement or enhancement to this https://github.com/nexB/scancode-toolkit/blob/develop/src/textcode/strings.py which is also Apache-licensed.

**Comment by mr-tz** [comment]
Thank you @daltonmatos and @pombredanne.

**Comment by daltonmatos** [comment]
You're welcome! :+1:
