### ISSUE TITLE
issue running floss in VM

### ISSUE THREAD

**Issue by totoroha** [fireeye/flare-floss#239]
Dear Team,
I'm running my VM with Windows 8 and having problem in running floss. This is the message that i received when i ran the program:
'floss.exe is not compatible with of the version of windows you're running'. I set the file in compatible mode with windows 8, and run as administrator.
Would you please help me in fixing this?

**Comment by williballenthin** [comment]
hi @totoroha 

would you please share the complete windows version you're running, as well as the version of FLOSS you have? this will help us reproduce the issue and triage the bug.

**Comment by totoroha** [comment]
![system properties](https://cloud.githubusercontent.com/assets/7328140/17445387/5a1695f2-5b0a-11e6-96fd-86344515dd8a.PNG)
My floss version is the most up to date which i downloaded a moment ago from here.

**Comment by williballenthin** [comment]
ok, the issue is that our FLOSS standalone binary is compiled for 64bit operating systems, and you are running 32bit windows.

**Comment by williballenthin** [comment]
i'm going to try to reconfigure our build service to also produce 32bit standalone binaries, so you can try FLOSS in your vm. waiting on the results of: https://github.com/fireeye/flare-floss/pull/240

**Comment by williballenthin** [comment]
@totoroha 

you can download 32bit standalone binaries here: http://s3.amazonaws.com/build-artifacts.floss.flare.fireeye.com/appveyor/dist/floss32.exe
