### ISSUE TITLE
error while running floss in VM

### ISSUE THREAD

**Issue by totoroha** [fireeye/flare-floss#244]
Dear Team,
Two weeks ago, I reported an error while running Floss with VM. With the assistance from Willi, he reconfigured build service and created a 32bit version for my vmware. I hadn't had a chance to tried it since then, so today I tried with my VM and everything is working except with some minor DLL errors.

I attached with this report a screenshot of the error. Please advise me what to do next.
![floss error](https://cloud.githubusercontent.com/assets/7328140/17556874/a56614e6-5eda-11e6-8a8a-f103d2b86bea.jpg)

**Comment by mr-tz** [comment]
Seems to be related to issue #241.

**Comment by mr-tz** [comment]
Fixed a typo via #245. Nightly builds work again.

**Comment by totoroha** [comment]
Thanks Team

My build is for 32bit stand alone. Not sure if it's applied for issue #241.

**Comment by mr-tz** [comment]
I just tested the 32-bit standalone executable again. Does it still fail for you? What error message do you get?

**Comment by totoroha** [comment]
[image: Inline image 1]

**Comment by mr-tz** [comment]
It looks like your image did not get included properly.

**Comment by totoroha** [comment]
what do you mean by not included properly? How do i fix it?

**Comment by williballenthin** [comment]
please use the web interface for github to post the image. use the following link: https://github.com/fireeye/flare-floss/issues/244
