### ISSUE TITLE
Simple xor not handled

### ISSUE THREAD

**Issue by Maijin** [fireeye/flare-floss#246]
Greetings,

Just tried floss with https://virustotal.com/en/file/f15985a91b12e015812f7f960eb0abe03d0cd401f54d0088f75cb087776a297c/analysis/ (http://radare.today/posts/malware-static-analysis/)

Floss should be able to detect that there is a xor 0xbc routine at bb 0x4061bd.

**Comment by mr-tz** [comment]
Thanks, FLOSS identifies the routine correctly, but fails during emulation around here:

```
DEBUG:Monitor:prehook: prehook: 0x4019b7 <vivisect.impemu.platarch.windows.Windowsi386Emulator instance at 0x7fb951544cf8> call 0x00401178
DEBUG:Monitor:apicall: apicall: <viv_utils.emulator_drivers.DebuggerEmulatorDriver object at 0x7fb9511d5510> call 0x00401178 4198776 ('int', None, 'stdcall', 'kernel32.InitializeCriticalSection', [('int', 'arg0')]) [4261300]
DEBUG:Monitor:prehook: prehook: 0x401178 <vivisect.impemu.platarch.windows.Windowsi386Emulator instance at 0x7fb951544cf8> jmp dword [0x00412188]
DEBUG:Monitor:prehook: prehook: 0x415bf000 <vivisect.impemu.platarch.windows.Windowsi386Emulator instance at 0x7fb951544cf8> False
DEBUG:floss:vivisect encountered an unexpected exception. will continue processing.
Traceback (most recent call last):
  File "decoding_manager.py", line 144, in emulate_function
    driver.runToVa(return_address, max_instruction_count)
  File "emulator_drivers.py", line 338, in runToVa
    self.stepi()
  File "emulator_drivers.py", line 298, in stepi
    return self.step(False)
  File "emulator_drivers.py", line 284, in step
    if self.isCall(op):
  File "emulator_drivers.py", line 109, in isCall
    return bool(op.iflags & v_envi.IF_CALL)
AttributeError: 'bool' object has no attribute 'iflags'
```

Hopefully, we'll be able to triage this issue soon.

**Comment by alrawi** [comment]
Yep, same issue. sample 83d14ce2dcfc852791d20cd78066ba5a2b39eb503e12e33f2ef0b1a46c68de73

Simple rolling XOR that can be easily emulated with Bochs, but no dice.

**Comment by williballenthin** [comment]
i'm going to split these issues up so they are easier to track.

@Maijin, your original issue will continue to be discussed here.

@alrawi, your issue will be discussed here: https://github.com/fireeye/flare-floss/issues/261

**Comment by williballenthin** [comment]
as noted above, FLOSS correctly identifies the decoding routine at 0x406188.

the issue appears to be in the emulation of the delphi runtime function invoked prior to each XOR instruction at 0x4061C0:

```
│      ┌──> 0x004061bd      8d45fc         lea eax, [ebp - buf]                                                                                                                                                    
│      |│   0x004061c0      e8a7daffff     call delphi_ref_junk        ;[3]                                                                                                                                        
│      |│   0x004061c5      8b55fc         mov edx, dword [ebp - buf]                                                                                                                                              
│      |│   0x004061c8      8a541aff       mov dl, byte [edx + ebx - 1]                                                                                                                                            
│      |│   0x004061cc      80f2bc         xor dl, 0xbc                                                                                                                                                            
│      |│   0x004061cf      885418ff       mov byte [eax + ebx - 1], dl                                                                                                                                            
│      |│   0x004061d3      43             inc ebx                                                                                                                                                                 
│      |│   0x004061d4      4e             dec esi                                                                                                                                                                 
│      └──< 0x004061d5      75e6           jne 0x4061bd                ;[4] 
```

although it appears like a simple refcount routine, its actually quite complex. see attached image of the callgraph.

![screenshot from 2017-03-15 21-15-29](https://cloud.githubusercontent.com/assets/156560/23977438/9671a4d8-09c4-11e7-875a-87425dee6a33.png)

it may be possible to correctly handle this function by adding the appropriate hooks for:
  - `InitializeCriticalSection`
  - `EnterCriticalSection`
  - `LeaveCriticalSection`
  - `VirtualFree`
  - `VirtualAlloc`
  - `LocalAlloc`

however, i have a suspicion there's a statically-linked malloc function in here. if so, this is not something we're going to support (malloc probably initialized during program setup, state that we can't feasibly capture). will report once i know a bit more.

**Comment by williballenthin** [comment]
yeah, i think the function at 0x4019a0 is a memory allocator. it seems to be allocating a chunk of memory using `LocalAlloc` (within a critical section) and manipulating free lists.

FLOSS will not support this sample. its very tricky to capture runtime state of things like statically-linked allocators. it may be possible to identify such routines using something like FLIRT or zignatures, but we don't have this yet.
