### ISSUE TITLE
floss32 vmware error

### ISSUE THREAD

**Issue by totoroha** [fireeye/flare-floss#250]
This is the error that i encountered from analyzing a malware sample.
![floss32 error](https://cloud.githubusercontent.com/assets/7328140/18524953/481adae4-7a80-11e6-965b-de6a41d98006.PNG)

**Comment by mr-tz** [comment]
What version of FLOSS are you running (floss32.exe --version)? Does this happen using the latest build available at http://s3.amazonaws.com/build-artifacts.floss.flare.fireeye.com/appveyor/dist/floss32.exe?

**Comment by totoroha** [comment]
This floss is produced by FireEye for me for 32bit vmware.

**Comment by mr-tz** [comment]
Can you provide the output of floss32.exe --version?

**Comment by totoroha** [comment]
floss32.exe 46983ca. This is the output of version command. Sorry for my
late response.

**Comment by williballenthin** [comment]
the error you encountered is a known issue that has already been fixed in later versions (673e7096f). please download the latest version from [here](http://s3.amazonaws.com/build-artifacts.floss.flare.fireeye.com/appveyor/dist/floss32.exe) and try again.
