### ISSUE TITLE
flare-floss on docker

### ISSUE THREAD

**Issue by lordx86** [fireeye/flare-floss#260]
can we make it available in docker as well?

**Comment by williballenthin** [comment]
hey @lordx86 

Thanks for the suggestion. Below is a Dockerfile that you can use to run FLOSS in Docker. Fortunately, its pretty trivial, and should be easy to tweak.

```
from python:2.7

RUN pip install https://github.com/williballenthin/vivisect/zipball/master
RUN mkdir /src && \
    git clone https://github.com/fireeye/flare-floss /src/flare-floss
RUN pip install -e /src/flare-floss

ENTRYPOINT ["/usr/local/bin/floss"]
```

### build
```
docker build -t flare/floss .
```

### size
```
$ docker images                
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
flare/floss             latest              821fd1acf11d        2 minutes ago       732.5 MB
```

it's a bit larger than I'd like, but the `docker.io/python` image is already more than 600MB.

### run
```
$ docker run -ti --rm -v $(pwd):/samples:z flare/floss /samples/bad.exe_
FLOSS static ASCII strings
!This program cannot be run in DOS mode.
@Rich)
.text
`.rdata
@.data
.rsrc
@.reloc
...
```

using `-v` to map the current directly to `/samples`. using `:z` to automatically configure selinux (useful on fedora & friends).


how does this work for you?

**Comment by lordx86** [comment]
hi Will, this is awesome ! thank you. will see how we can add it to this list:
https://hub.docker.com/r/remnux/
