### ISSUE TITLE
List type and key if possible

### ISSUE THREAD

**Issue by jeffg2k** [fireeye/flare-floss#288]
Wondering if you might also be able to list the encoding / encryption method and the key when outputting the decoded string.  Such that if it used XOR with a static key, it would state that and what the key was to decode the string.

**Comment by mr-tz** [comment]
FLOSS identifies the decoding mechanisms using heuristics and performs emulation of the identified functions. Hence, it never has to be concerned with any details of the decoding itself and does not provide more information.

However, if you use the `-g` command-line options FLOSS will show you the decoding function offset. If you use the `-x` command-line option, the output will also include where a function has been called from. This will hopefully help in identifying the decoding algorithm and key.
