### ISSUE TITLE
Fails to decode / deobsfuscate Mach-O binary

### ISSUE THREAD

**Issue by ParityError** [fireeye/flare-floss#297]
I was attempting to make sense of the obfuscation in the following Mach-O binary:

https://github.com/skeyboy/newBG/blob/master/soft/iThoughtsX%202.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/libConfigurer64.dylib

I came up empty with floss - any suggestions on how to proceed?

**Comment by williballenthin** [comment]
FLOSS can help you with string obfuscation; however, it does not yet support Mach-O binaries. The underlying binary analysis framework does not understand the file format very well. While its a feature we may add in the future, its not available yet.
