### ISSUE TITLE
A string sorting option would be great

### ISSUE THREAD

**Issue by BenjaminSoelberg** [fireeye/flare-floss#303]
May I suggest to add an option to specify the sort order of displayed strings.
I think that Unsorted, Alphabetical (and maybe Natura) sorting types would be great to have.

**Comment by mr-tz** [comment]
What's the benefit you see over piping FLOSS' output to sort?
For example: `floss -q [other options] sample.exe | sort`

**Comment by BenjaminSoelberg** [comment]
That is a very good question, I can't really think of it right now.
