### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by b0urb0n** [fireeye/flare-floss#305]
Is there any effort toward porting this project to Python 3?

It doesn't look like `vivisect` is being ported to Python 3 which doesn't help.  I was just curious if it was on your radar.

**Comment by williballenthin** [comment]
I would love to, especially as many of the services that I rely on internally have moved to py3.

But, as you mentioned, vivisect is py2 only.

I think it may be feasible to migrate to something like unicorn, but then we'd still need a code analysis component to find functions, etc. So, I think its unlikely that FLOSS will migrate before the py2-pocalpse (2020).

**Comment by dadokkio** [comment]
any update on this topic?

**Comment by williballenthin** [comment]
vivisect is still py2, so no updates. there's bit a little movement over the past few months towards py3, but its not there yet.

**Comment by rakuy0** [comment]
Aye. Working on porting vivisect to py3. @williballenthin I'll let you know when the PR is ready for review (it's this one: https://github.com/vivisect/vivisect/pull/271)

**Comment by b0urb0n** [comment]
Looks like https://github.com/vivisect/vivisect/pull/328 was merged (congrats @rakuy0)

**Comment by williballenthin** [comment]
yeah, we're excited!

to be direct, we'll be focusing on some capa features in the near term and getting that up to speed with py3. then, we will turn attention to floss. moritz and i discuss floss during each one of our bi-weekly 1:1s ;-)

**Comment by b0urb0n** [comment]
I'd be happy to help out where I can!

**Comment by MiracDasmine** [comment]
I am still getting this error
ERROR: Could not find a version that satisfies the requirement vivisect==0.1.0 (from flare-floss)
ERROR: No matching distribution found for vivisect==0.1.0
How do I go about it?

**Comment by mr-tz** [comment]
Currently, `floss` only runs with Python 2.

If anyone wants to submit a PR to `futurize` the current code base, that could give us a head start. 🙇
