### ISSUE TITLE
Linux: v1.5.0 - version incorrect - not as advertised

### ISSUE THREAD

**Issue by evandrix** [fireeye/flare-floss#310]
The download [https://github.com/fireeye/flare-floss/releases/download/v1.5.0/floss-1.5.0-GNU.Linux.zip](https://github.com/fireeye/flare-floss/releases/download/v1.5.0/floss-1.5.0-GNU.Linux.zip) claims to be v1.5.0, but is, in fact:

```
$ floss --version
floss v1.4.0-55-g8064cda
https://github.com/fireeye/flare-floss
```

:gasp: !

**Comment by mr-tz** [comment]
Oh, good catch. Sorry for the confusion. The binary was created vi CI before I created the `v1.5.0` tag on commit ab8f775.
So the version is off, but the file is actually version 1.5.0.
