### ISSUE TITLE
use StringSifter to order strings

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#314]
[StringSifter](https://github.com/fireeye/stringsifter) is a machine learning utility to recognize which strings are probably interesting to malware analysts. Per string, it provides a score for "interesting-ness". We can pass each recovered string through StringSifter and collect the scores. Then, we can output strings such that the most relevant show up at the top.

There might be other ways of grouping strings, such as "by decoding routine", "location in file", etc. I think StringSifter will be a good default, though.

**Comment by williballenthin** [comment]
ugh 
![image](https://user-images.githubusercontent.com/156560/66362723-12db0380-e941-11e9-8f73-04ce2afc5171.png)

**Comment by mr-tz** [comment]
StringSifter explains how to use both tools in tandem to achieve this.
