### ISSUE TITLE
FLOSS reporting incorrect version?

### ISSUE THREAD

**Issue by evandrix** [fireeye/flare-floss#319]
i downloaded https://github.com/fireeye/flare-floss/releases/download/v1.5.0/floss-1.5.0-OSX.zip, and ran `floss --version`:
```
floss v1.4.0-59-gfe38f10
https://github.com/fireeye/flare-floss/
```

???

**Comment by mr-tz** [comment]
Please download an updated version from our [nightly builds](https://s3.amazonaws.com/build-artifacts.floss.flare.fireeye.com/travis/osx/dist/floss).
