### ISSUE TITLE
ERROR:floss:Vivisect failed to load the input file: No module named entrypoints 

### ISSUE THREAD

**Issue by DigiAngel** [fireeye/flare-floss#320]
FYI after latest vivisect git pull.

**Comment by williballenthin** [comment]
good catch. this is due to upstream viv changes.

**Comment by DigiAngel** [comment]
Thank you!

**Comment by williballenthin** [comment]
should be addressed in 4fd255b4eb767b744336cc352ee868cdd620668b

lets see how CI/CD goes.
https://travis-ci.org/github/fireeye/flare-floss/builds/673101659

**Comment by DigiAngel** [comment]
Thank you...any chance this will be in the precompiled version soon?

**Comment by DigiAngel** [comment]
Latest build works great thank you!
