### ISSUE TITLE
Export strings into a JSON report

### ISSUE THREAD

**Issue by b0urb0n** [fireeye/flare-floss#322]
I would like the FLOSS CLI tool to have the ability to generate a report that captures all the strings extracted during analysis.

I used to accomplish this by using FLOSS as a Python2.7 library but my team has made the hard switch to Python3.  Because of this, FLOSS now runs as a `subprocess` and I have to parse the output.  Adding the ability to write the results of analysis to a file would benefit my effort and would likely be a welcomed feature by others.

PR: #321

**Comment by mr-tz** [comment]
closed via #321

**Comment by williballenthin** [comment]
🎈
