### ISSUE TITLE
JSON output option doesn't work if the binary isn't a PE

### ISSUE THREAD

**Issue by fishtek** [fireeye/flare-floss#325]
Hey guys, I noticed the recently added `--output-json` option that @b0urb0n added and wanted to give it a shot.  I like to use FLOSS as a drop in replacement for 'strings' and so it turns out I was just running it against random binaries and not PE files and so a `WorkspaceLoadError` was [occurring around line 1061](https://github.com/fireeye/flare-floss/blob/master/floss/main.py#L1061), so all the code after that including the output-json option wasn't working.

Any chance we can make a fix so that'll work?

**Comment by mr-tz** [comment]
Oh, yes. Good catch! `create_json_output` never gets executed towards the end of main. We will address this soon.
