### ISSUE TITLE
No module named instrhoook with latest nightly

### ISSUE THREAD

**Issue by DigiAngel** [fireeye/flare-floss#333]
Topic:
~~~
ERROR:floss:Vivisect failed to load the input file: No module named instrhook
~~~

strings work fine, but the stack string decode fails with the above.

**Comment by DigiAngel** [comment]
Hash of sample being looked at (should be everywhere...not VT though ;) ):
~~~
15f292d3edec1c064cbde19f7d0df8e891cfd3d61a3982f952b3d3d1d39d2755
~~~

**Comment by williballenthin** [comment]
`instrhook` was added very recently to vivisect [here](https://github.com/vivisect/vivisect/pull/284).

have you installed vivisect from the upstream repo? if so, that might be the bug. if not, then our snapshot of vivisect isnt working quite right.

thanks for reporting this issue! i'll dig into it on our end.

**Comment by williballenthin** [comment]
upstream viv has the import statement:
![image](https://user-images.githubusercontent.com/156560/85355211-58d4f900-b4c9-11ea-811e-66d5838605c9.png)

and the module is there:
![image](https://user-images.githubusercontent.com/156560/85355230-625e6100-b4c9-11ea-83ed-8a39812ea9a2.png)

ah, but our pyinstaller spec doesn't have a reference yet:
![image](https://user-images.githubusercontent.com/156560/85355257-77d38b00-b4c9-11ea-84e6-e682ac01e782.png)


this is a floss bug.

@rakuy0 @atlasofdoom another example of vivisect dynamic imports breaking our build. of course as we've discussed, its still our problem, cause this is the solution we've gone with (maintaining the pyinstaller spec), but its a tiny bit annoying we can't rely on static analysis of viv to find the code to package up.

**Comment by williballenthin** [comment]
@DigiAngel would you mind trying with the latest nightly once CI builds (in 5-10 mins)?

**Comment by williballenthin** [comment]
@atlas0fd00m i broke your handle earlier (since edited) so notification probably didn't go out. sorry.

**Comment by DigiAngel** [comment]
Fixed up..thank you!

**Comment by rakuy0** [comment]
@williballenthin  Yea. It is a bit annoying to have the dynamic imports break things whenever we want to add a new file.

I'm gonna look into changing around how we do our analysis importing soon. See if there's better way for both of us.
