### ISSUE TITLE
--ida option doesn't work with IDA 7.4

### ISSUE THREAD

**Issue by Ana06** [fireeye/flare-floss#335]
Some of the used methods have been renamed in IDA 7.4: https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

It is not difficult to fix this, the question is: do we want to keep this option?

If Floss could run in Python3, a better approach would be to just provide a json output, as an ida script/plunging could call floss. Taking into account that this is not an option and that this script is really useful, I would fix it. Most likely we want to have a plugin for < 7.3 and one for >= 7.4.

Related to https://github.com/fireeye/flare-floss/issues/328

**Comment by mr-tz** [comment]
I think the larger rework will take some time and a short-term fix will be helpful to many people.

If you have a moment, we'd appreciate a PR to change to the new IDAPython API (>IDA 7.0). I don't think we have to keep supporting the legacy API at this point.

**Comment by Ana06** [comment]
I'll send a PR 👍
