### ISSUE TITLE
Cannot open file issue

### ISSUE THREAD

**Issue by DigiAngel** [fireeye/flare-floss#339]
Using floss v1.6.1-32-g1e728e4 and:
~~~
commit a03d4d0cfd7278d60bc0222ec032235153cf0258 (HEAD -> master, tag: v0.1.0rc1, origin/master, origin/HEAD)
Date:   Wed Jul 29 22:38:21 2020 -0400
~~~
vivisect I now see:
~~~
ERROR:floss:Vivisect failed to load the input file:
~~~
for decoding stack strings.  Strings of the file still show up fine though.  Thank you!

**Comment by mr-tz** [comment]
Can you provide a test sample or alternatively some details on the file (type, architecture, etc.) you're analyzing?

How are you running `floss`, e.g. `floss sample.exe`?

**Comment by DigiAngel** [comment]
Any file...say 6978d5205387391748ee7e9facf1ae607c37fbfd83b77cb632dd772f8d71a165 (ddraw.dll from Win7).  On ubuntu linux 18 x64.  Just running:
~~~
floss ddraw.dll
~~~
![Screenshot from 2020-07-31 04-36-23](https://user-images.githubusercontent.com/947191/89027368-9bb79700-d2e7-11ea-8e2b-ff46fe905cac.png)

**Comment by mr-tz** [comment]
Got it. Thanks!

This is related to https://github.com/williballenthin/viv-utils/issues/11

For now, will revert to previous vivisect and viv-utils.

**Comment by DigiAngel** [comment]
Awesome...thank you!

**Comment by mr-tz** [comment]
Well, unfortunately reverting takes a little more effort 🙈 In the meantime I hope you can run it directly via Python, see https://github.com/fireeye/flare-floss/blob/master/doc/installation.md#method-2-using-floss-as-a-python-library.

**Comment by DigiAngel** [comment]
Thanks...I'll give that a go.

**Comment by Dump-GUY** [comment]
I must confirm the issue:
With latest version (floss64.exe 1e728e4):
No matter what you run - result: ERROR:floss:Vivisect failed to load the input file:

With older version all functional (floss64.exe eb30be5)

Sample included - password:infected
[kpot2.zip](https://github.com/fireeye/flare-floss/files/5009078/kpot2.zip)

**Comment by mr-tz** [comment]
also needed #342, please try out the updated nightly builds in a couple of minutes
