### ISSUE TITLE
FLOSS fails against free obfuscator

### ISSUE THREAD

**Issue by Nametrial** [fireeye/flare-floss#346]
I discovered a free obfuscator online (Phoenix Protector) which is available [here ](https://ntcore.com/?page_id=384).  According to the help page, it's copyright 2006.  The last dated update is from December 11, 2008 (version 1.6) and the current version is 1.8.0.1.  
TL;DR this is very old in the world of obfuscation and it's totally free

I ran a DLL through it with String Obfuscation enabled, and tested FLOSS against that DLL.  It doesn't give me Malayalam numerals like IDA does, but FLOSS still shows mangled strings of inappropriate lengths instead of the strings I embedded in the DLL.

Just for giggles, I compared the FLOSS output using the obfuscated DLL with the FLOSS output on the regular DLL.  Works fine, when no protection is used.

FLOSS can't beat a free obfuscator from circa 2006.  Any malware-maker worth their weight in code should be able to find this free program so perhaps the contributors of this project should find a way to beat Phoenix Protector.

**Comment by mr-tz** [comment]
Unfortunately FLOSS doesn't perform any string deobfuscation for .NET binaries. I'll open an issue to warns the user like we do with capa.
