### ISSUE TITLE
v1.7.0 release notes

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#359]
v1.7.0

adds:
  - static string json output format @mr-tz
  - test case invoking main @mr-tz
  - tests via GH actions @mr-tz
  - builds via GH actions @williballenthin

changes:
  - package relative imports @b0urb0n
  - register tests in setup.py @b0urb0n
  - vivisect version @r0ny123
  - code style via black, isort @mr-tz
  - test files in sub repo @mr-tz

fixes:
  - vivisect pyinstaller @williballenthin
  - IDA 7.4+ support @Ana06
  - strings algorithm via bytes @jedimasterbot

changes: [v1.6.1...v1.7.0](https://github.com/fireeye/flare-floss/compare/v1.6.1...v1.7.0)

**Comment by williballenthin** [comment]
@mr-tz @Ana06  review please

**Comment by mr-tz** [comment]
Looks great, thanks a lot!

If it's easy, let's add #344. If not, next time.

**Comment by Ana06** [comment]
I only tried that FLOSS is working in IDA 7.4 and not in 7.5. I don't see anything in [IDA 7.5 release notes](https://www.hex-rays.com/products/ida/news/7_5/) which should break FLOSS, but I haven't tried it (not sure if someone else has). It may be anyway a good idea to mention IDA 7.4 in FLOSS 1.7.0 release notes, just to make clear this is the first version which works with IDA 7.4. 🤔

Apart from that, it looks good to me! 👍
