### ISSUE TITLE
Configure viv emulator taint byte to non-ASCII character

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-floss#360]
Implemented in https://github.com/vivisect/vivisect/pull/365

From https://github.com/vivisect/vivisect/pull/156
> It would be handy if the memory taint byte for the emulator could be configurable. For example, during function emulation in FLOSS we would like to set the taint byte to a value outside of the ASCII range. This allows us to easier distinguish between tainted memory and decoded strings.

**Comment by williballenthin** [comment]
this will require migrating to py3 viv

**Comment by mr-tz** [comment]
@Ana06 😉
