### ISSUE TITLE
Provide json as base output

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-floss#385]
FLOSS should use a standardized json base output to enhance interoperability with external tools and ease the various output modes (cmd line, IDA script, etc.).

related: #188

**Comment by mr-tz** [comment]
As a counter point (?) it would be nice if FLOSS would output strings as it encounters/deobfuscates them.

**Comment by williballenthin** [comment]
> As a counter point (?) it would be nice if FLOSS would output strings as it encounters/deobfuscates them.

we could use logging status messages to STDERR for this and keep the final output to STDOUT at the end
