### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by williamgibb** [fireeye/flare-floss#4]
Unit tests fail since they rely on binaries which are not present in the git repo.  Furthermore, not all of the binaries used for unit tests are present in VirusTotal, preventing anyone with VTI access from actually reproducing the full suite of unit tests.

Can you select binaries which are publicly shared and include them in the repo?  Possibly under tests/assets/binaries/* ?

**Comment by williballenthin** [comment]
Issue acknowledged. Probably won't include the test files in the repo since they will probably (correctly) be flagged as malware upon checkout. 

Potential solution: provide a download script to fetch and initialize samples from VT given an API key.

**Comment by mr-tz** [comment]
Thanks, we will provide benign testing binaries and update the test cases.

**Comment by mr-tz** [comment]
See new testing architecture, documentation, and travis integration
