### ISSUE TITLE
Remove pVA prefix in string output

### ISSUE THREAD

**Issue by mr-tz** [fireeye/flare-floss#62]
For decoded strings and stackstrings, e.g., sample c5de...868e

**Comment by williballenthin** [comment]
maybe by moving the stack and heap sections we can reduce the incidence of ASCII bytes in pointers?

**Comment by mr-tz** [comment]
I'm not sure what you mean by 'moving the stack and heap sections'. Can you elaborate?

**Comment by williballenthin** [comment]
what happens if we require strings to start on aligned addresses? especially if the prefix is something like `pVA` and unaligned, we could do something intelligent.

alternatively, could check some of those bytes for vivisect taint? need to do some research.

**Comment by mr-tz** [comment]
AAAA... strings come from vivisect's memory initializing to 0x41414141.

VA strings must be related to taint in the emulator:
```
./vivisect/impemu/emulator.py:38:        self.taintva = itertools.count(0x41560000, 8192)
[...]
return self.taintva.next() + 4096
```

```
>>> a = itertools.count(0x41560000, 8192)                                       
>>> n = a.next()+4096; chr((n&0xFF000000)>>24); chr((n&0x00FF0000)>>16); chr((n&0x0000FF00)>>8)
'A'
'V'
'\x10'
>>> n = a.next()+4096; chr((n&0xFF000000)>>24); chr((n&0x00FF0000)>>16); chr((n&0x0000FF00)>>8)
'A'
'V'
'0'
>>> n = a.next()+4096; chr((n&0xFF000000)>>24); chr((n&0x00FF0000)>>16); chr((n&0x0000FF00)>>8)
'A'
'V'
'P'
>>> n = a.next()+4096; chr((n&0xFF000000)>>24); chr((n&0x00FF0000)>>16); chr((n&0x0000FF00)>>8)
'A'
'V'
'p'
>>> n = a.next()+4096; chr((n&0xFF000000)>>24); chr((n&0x00FF0000)>>16); chr((n&0x0000FF00)>>8)
'A'
'V'
'\x90'
>>> n = a.next()+4096; chr((n&0xFF000000)>>24); chr((n&0x00FF0000)>>16); chr((n&0x0000FF00)>>8)
'A'
'V'
'\xb0'
>>> n = a.next()+4096; chr((n&0xFF000000)>>24); chr((n&0x00FF0000)>>16); chr((n&0x0000FF00)>>8)
'A'
'V'
'\xd0'
>>> n = a.next()+4096; chr((n&0xFF000000)>>24); chr((n&0x00FF0000)>>16); chr((n&0x0000FF00)>>8)
'A'
'V'
'\xf0'
```

**Comment by mr-tz** [comment]
Your first idea could be a quick win!

**Comment by mr-tz** [comment]
Another idea, not necessarily related to this issue, but might help with other false positives (the return address). We could try to take the first snapshot one instruction later than currently, i.e., while the emulator is at the decoding routine's first instruction. I'm not sure about the actual benefit vs. the required changes.

**Comment by williballenthin** [comment]
interesting idea. would require the following:

move this line:

https://github.com/fireeye/flare-floss/blob/master/floss/decoding_manager.py#L108

to around 114.

since we're using a `DebuggerEmulatorDriver`, we can use the `.stepi()` method to single step once, assuming the first instruction is a `call`.

**Comment by williballenthin** [comment]
or we could do a regex replace on "^pVA+$" and simply remove hits
