### ISSUE TITLE
document testing architecture

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#67]
especially how we store the test data appended to the sample. schema etc. how to run a test on a file. writing a new test.

**Comment by williballenthin** [comment]
feel free to break this issue into smaller sub-issues and re-assign them

**Comment by mr-tz** [comment]
- [ ] format of appended data
  - [ ] how submit an issue (sample that's not working)

**Comment by williballenthin** [comment]
not using the appended data test cases anymore, so not as relevant.

**Comment by mr-tz** [comment]
Yes and the existing test cases are straightforward.
