### ISSUE TITLE
oss: define database format

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#714]
want to be able to lookup from string to library details.

desirable fields:
  - library name
  - library version
  - file name
  - function name

might also be nice to have a hyperlink to a source location on github codesearch, but this is not priority.

**Comment by williballenthin** [comment]
maybe we should use the jsonl format (rather than wrapping the list in [] then each line is implied to be a json object). this way we can easily concatenate the database files together.

**Comment by williballenthin** [comment]
database sizes for some libraries i had previously processed:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/156560/236175861-2465187e-ddf1-42de-86e8-936b9836cb0c.png">

**Comment by williballenthin** [comment]
proposing
https://github.com/mandiant/flare-floss/blob/4bdf5c93afdf5ebc36b9d30914fd6e6eeb3d0499/floss/qs/db/oss.py#L9-L35
and tests https://github.com/mandiant/flare-floss/blob/quantumstrand/tests/test_oss_db.py

in [4bdf5c9](https://github.com/mandiant/flare-floss/commit/4bdf5c93afdf5ebc36b9d30914fd6e6eeb3d0499)

ok @mr-tz ?

**Comment by mr-tz** [comment]
one additional case are open source strings that we still extract from binaries, for those `file_path` (and maybe `function_name`) may be unavailable or differ, we can add a new class for those though

**Comment by williballenthin** [comment]
good point, i'll mark file name and function name as optional, too
