### ISSUE TITLE
identify rust runtime strings from rust compiler source code

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-floss#766]

**Comment by williballenthin** [comment]
related to #762

**Comment by williballenthin** [comment]
consider searching for the strings in #762 via github codesearch cs.github.com and then sharing the hyperlinks here

**Comment by williballenthin** [comment]
"from_str_radix_int: must lie in the range `[2, 36]` - found"

<img width="428" alt="image" src="https://github.com/mandiant/flare-floss/assets/156560/80a25eb5-fac5-4426-9992-e0c9a622a4e9">

https://github.com/rust-lang/rust/blob/e29821ff85a2a3000d226f99f62f89464028d5d6/library/core/src/num/mod.rs#LL1442C1-L1446C7


"note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

<img width="566" alt="image" src="https://github.com/mandiant/flare-floss/assets/156560/3d144719-c909-4f28-88b4-ed9a41fbf1f3">

https://github.com/rust-lang/rust/blob/e29821ff85a2a3000d226f99f62f89464028d5d6/library/std/src/panicking.rs#L275

"note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace."

<img width="394" alt="image" src="https://github.com/mandiant/flare-floss/assets/156560/b1c36cc4-bef3-4b09-9df1-f203e201ffae">


https://github.com/rust-lang/rust/blob/e29821ff85a2a3000d226f99f62f89464028d5d6/library/std/src/sys_common/backtrace.rs#L120C1-L121

**Comment by williballenthin** [comment]
> would it be accurate to say that strings in "panicking.rs" has to be present in every Rust binary?

I suspect this is probably the case for most/all PE files. there are some alternative options for embedded rust, but i wouldn't expect these to be used in PE files. some more related details: https://docs.rust-embedded.org/book/start/panicking.html

**Comment by williballenthin** [comment]
i think this might be one other file we want to include coverage for: https://github.com/rust-lang/rust/blob/e29821ff85a2a3000d226f99f62f89464028d5d6/library/std/src/rt.rs

i believe this is where the first functions that get executed are in a PE file.

**Comment by mr-tz** [comment]
Very cool, so looks like we can start with identifying:
- `rustc/<commit_hash>` -> version
- `rustc/<version_string>` -> version

And I think we may still want to include some of the other strings you've identified above, just in case.

**Comment by wballenthin** [comment]
> would it be accurate to say that strings in "panicking.rs" has to be present in every Rust binary?

> [By default](https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles), when Rust code encounters a situation when it must call panic!(), it unwinds the stack and produces a helpful backtrace. The unwinding code, however, does require extra binary size. rustc can be instructed to abort immediately rather than unwind, which removes the need for this extra unwinding code.

https://github.com/johnthagen/min-sized-rust#abort-on-panic
