### ISSUE TITLE
Analyzing the .text Segment in a Go Binary

### ISSUE THREAD

**Issue by Arker123** [fireeye/flare-floss#805]
This issue involves the analysis of the .text segment within a Go binary. The focus is on understanding the strings contained in the .text segment.

This issue is a continuation of the discussion in https://github.com/mandiant/flare-floss/issues/779

**Comment by mr-tz** [comment]
Cool, I think that's a good start for an optimization for short strings.

A few follow up questions:
1. Have you looked at other binaries? Here the instruction is `cmp` but we want to handle others, e.g., `mov` as well.
2. What about strings that are longer than 8/16 characters? I think that case is actually easier (that's why I suggested to skip case 3 originally in https://github.com/mandiant/flare-floss/issues/779#issuecomment-1581047424).

**Comment by mr-tz** [comment]
Have you checked out the code of various Go binaries (different source) to see how strings are stored and accessed?

**Comment by williballenthin** [comment]
"strings in the .text segment"

from here: https://stackoverflow.com/a/35342389
we are linked to this commit in the Go compiler: https://github.com/golang/go/commit/69cd91a5981c49eaaa59b33196bdb5586c18d289
which introduces an optimization in Go 1.5 for comparing a string with a constant string. in this scenario. the constant string is converted to a stack-allocated temporary byte[] variable, which leads to inlining like seen in the above examples. im not sure yet where the decision to use 8 vs 16 bytes as the max inline size is, but its possible thats its far away in the compiler source.

anyways, this clarifies which strings we expect to see in this pattern: string constants used during map lookup, constant concatenation, and comparisons
https://github.com/golang/go/blob/c3db64c0f45e8f2d75c5b59401e0fc925701b6f4/src/runtime/string.go#L146-L149

**Comment by mr-tz** [comment]
> In versions preceding Go 1.6, while analyzing the .text segment, it is observed that the reference to the string exists, but the string length information is not readily accessible.

As per our discussion we're not targeting versions <1.6 to focus on more recent versions. But please add an issue with some details like sample (hash) and what you've learned so far.

**Comment by mr-tz** [comment]
Interesting, which samples have you analyzed above?

**Comment by mr-tz** [comment]
Great, would love to see the current performance (via the analysis script) on
1. our testfiles across Go versions and
2. a bunch of random Go samples

Ideally we also script/automate this and integrate into our tests (CI), see #807
